### ISSUE TITLE
add support for device changes events

### ISSUE THREAD

**Issue by benoitc** [benoitc/erlang-nat#10]
UPNP, PMP and PCP allows the user to receive broadcasted events when their address change. This would allow the application to eventually broadcast a new external address if needed.

## TODO

support the following specs:

- [ ] * upnp : http://upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v1.1.pdf (1.2.4)
- [ ] * PMP: https://tools.ietf.org/html/rfc6886#section-9.6
- [ ] * PCP: https://tools.ietf.org/html/rfc6887#section-11.5
